# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6d96e3148cf3ab724c6e71eddbb97837"
name = "Tessanda Teppich Konfigurator"
application_url = "https://tessanda.tradeumcloud.ch"
embedded = false

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
scopes = "write_themes"

[auth]
redirect_urls = [ "https://tessanda.tradeumcloud.ch/auth/callback" ]

[[extensions]]
  type = "theme"
  name = "carpet-configurator"
  handle = "carpet-configurator"
